version: '3.8'

services:
  nationwide-home-buyers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nationwide-home-buyers
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_EMAILJS_SERVICE_ID=${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
      - NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}
      - NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nationwide-home-buyers-rtr.entrypoints=https"
      - "traefik.http.routers.nationwide-home-buyers-rtr.rule=Host(`nationwide-home-buyers.mjrflix.com`)"
      - "traefik.http.routers.nationwide-home-buyers-rtr.tls=true"
      - "traefik.http.routers.nationwide-home-buyers-rtr.service=nationwide-home-buyers-svc"
      - "traefik.http.services.nationwide-home-buyers-svc.loadbalancer.server.port=3000"
